export const SKILLS = [
  { title: 'Front Flip', imageUrl: '/img/sample.jpeg' },
  { title: 'Back Flip', imageUrl: '/img/sample.jpeg' },
  { title: 'Aerial', imageUrl: '/img/sample.jpeg' },
  { title: 'Hand Stand', imageUrl: '/img/sample.jpeg' },
  { title: 'Round Off', imageUrl: '/img/sample.jpeg' },
  { title: 'Cart Wheel', imageUrl: '/img/sample.jpeg' },
  { title: 'Back Handspring', imageUrl: '/img/sample.jpeg' },
  { title: 'Front Handspring', imageUrl: '/img/sample.jpeg' },
  { title: 'Back Tuck', imageUrl: '/img/sample.jpeg' },
  { title: 'Front Tuck', imageUrl: '/img/sample.jpeg' },
  { title: 'Side Flip', imageUrl: '/img/sample.jpeg' },
  { title: 'Side Aerial', imageUrl: '/img/sample.jpeg' },
  { title: 'Gainer', imageUrl: '/img/sample.jpeg' },
  { title: 'Webster', imageUrl: '/img/sample.jpeg' },
  { title: 'Cork', imageUrl: '/img/sample.jpeg' },
  { title: 'B Twist', imageUrl: '/img/sample.jpeg' },
  { title: 'A Twist', imageUrl: '/img/sample.jpeg' },
  { title: 'Double Full', imageUrl: '/img/sample.jpeg' },
  { title: 'Triple Full', imageUrl: '/img/sample.jpeg' },
  { title: 'Quad Full', imageUrl: '/img/sample.jpeg' },
  { title: 'Double Back', imageUrl: '/img/sample.jpeg' },
  { title: 'Triple Back', imageUrl: '/img/sample.jpeg' },
  { title: 'Quad Back', imageUrl: '/img/sample.jpeg' },
  { title: 'Double Front', imageUrl: '/img/sample.jpeg' },
  { title: 'Triple Front', imageUrl: '/img/sample.jpeg' },
  { title: 'Quad Front', imageUrl: '/img/sample.jpeg' },
  { title: 'Double Side', imageUrl: '/img/sample.jpeg' },
  { title: 'Triple Side', imageUrl: '/img/sample.jpeg' },
  { title: 'Quad Side', imageUrl: '/img/sample.jpeg' },
  { title: 'Double Aerial', imageUrl: '/img/sample.jpeg' },
  { title: 'Triple Aerial', imageUrl: '/img/sample.jpeg' },
  { title: 'Quad Aerial', imageUrl: '/img/sample.jpeg' },
  { title: 'Double Twist', imageUrl: '/img/sample.jpeg' },
]
